"""Agregar columna nombre_producto en DetalleVenta

Revision ID: 0d517864365e
Revises: 958972254f88
Create Date: 2026-02-17 16:04:43.742801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d517864365e'
down_revision: Union[str, Sequence[str], None] = '958972254f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalle_ventas', sa.Column('nombre_producto', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'ventas', ['id_venta'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ventas', type_='unique')
    op.drop_column('detalle_ventas', 'nombre_producto')
    # ### end Alembic commands ###
