"""create tables

Revision ID: 17973460f3e9
Revises: 41f872af46f5
Create Date: 2026-02-20 15:25:18.610770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17973460f3e9'
down_revision: Union[str, Sequence[str], None] = '41f872af46f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalle_ventas', 'cantidad',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalle_ventas', 'cantidad',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=3),
               existing_nullable=False)
    # ### end Alembic commands ###
