"""Hacer nombre_producto NOT NULL

Revision ID: 41f872af46f5
Revises: 0d517864365e
Create Date: 2026-02-17 16:29:24.110173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f872af46f5'
down_revision: Union[str, Sequence[str], None] = '0d517864365e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalle_ventas', 'nombre_producto',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalle_ventas', 'nombre_producto',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
