"""Create tables entradas

Revision ID: 6959ae2b4261
Revises: 17973460f3e9
Create Date: 2026-02-20 15:32:58.258668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6959ae2b4261'
down_revision: Union[str, Sequence[str], None] = '17973460f3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entradas',
    sa.Column('id_entrada', sa.VARCHAR(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('total_productos', sa.Integer(), nullable=False),
    sa.Column('total_unidades', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_entrada')
    )
    op.create_table('detalle_entradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_entrada', sa.VARCHAR(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.String(length=100), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['id_entrada'], ['entradas.id_entrada'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_entradas')
    op.drop_table('entradas')
    # ### end Alembic commands ###
