"""crear tablas ventas y detalle_ventas

Revision ID: 958972254f88
Revises: 38c1e755b2a9
Create Date: 2026-02-16 18:37:50.511647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958972254f88'
down_revision: Union[str, Sequence[str], None] = '38c1e755b2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventas',
    sa.Column('id_venta', sa.String(length=6), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_venta'),
    sa.UniqueConstraint('id_venta')
    )
    op.create_table('detalle_ventas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_venta', sa.String(length=6), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('usuarios', 'contrasena',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('usuarios', 'requiere_cambio',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'requiere_cambio',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('usuarios', 'contrasena',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_table('detalle_ventas')
    op.drop_table('ventas')
    # ### end Alembic commands ###
